const quizz = [
  {
    id: 1,
    q: "Khái niệm “cái gì còn lại khi tất cả những thứ đã mất đi , cái đó là văn hóa” là của ai",
    a: {
      A: "E. Heriot",
      B: "E. Horiet",
      C: "E. Heeiot",
      D: "E. Heriet",
    },
    s: "A",
  },
  {
    id: 2,
    q: "Văn hoá là tổng hoà những ___ cũng như các phương thức tạo ra chúng, kỹ năng sử dụng các giá trị đó vì sự tiến bộ của loài người và sự truyền thụ các giá trị đó tù thế hệ này sang thế hệ khác",
    a: {
      A: "Tôn giáo và tín ngưỡng",
      B: "Giá trị và thái độ",
      C: "Giá trị vật chất và tinh thần",
      D: "Phong tục và tập quán",
    },
    s: "C",
  },
  {
    id: 3,
    q: "Đâu không phải là đặc trưng của văn hóa",
    a: {
      A: "Tính Tập Quán",
      B: "Tính Cổ Truyền",
      C: "Tính Khách Quan",
      D: "Tính Kế Thừa",
    },
    s: "B",
  },
  {
    id: 4,
    q: "_____ làm cho mỗi con người trong xã hội có sự giống nhau và làm cho các xã hội khác biệt nhau",
    a: {
      A: "Thẩm mĩ",
      B: "Văn hoá",
      C: "Ngôn ngữ",
      D: "Giáo dục",
    },
    s: "B",
  },
  {
    id: 5,
    q: "Đây là đặc trưng nào của văn hóa: “Cùng một sự việc nhưng có thể được hiểu và đánh giá khác nhau bởi những người có nền văn hóa khác nhau“",
    a: {
      A: "VH mang tính cộng đồng",
      B: "Văn hóa có thể học hỏi",
      C: "VH mang tính khách quan",
      D: "VH mang tính chủ quan",
    },
    s: "D",
  },
  {
    id: 6,
    q: "“Triết lý kinh doanh là những tư tưởng chỉ đạo, định hướng, dẫn dắt hoạt động kinh doanh”. Đây là khái niệm triết lý kinh doanh theo:",
    a: {
      A: "Cách thức hình thành",
      B: "Yếu tố cấu thành",
      C: "Vai trò",
      D: "Nội dung",
    },
    s: "C",
  },
  {
    id: 7,
    q: ".........là phương châm hành động, là hệ giá trị và mục tiêu của Doanh nghiệp chỉ dẫn cho hoạt động kinh doanh",
    a: {
      A: "Văn hoá",
      B: "Triết lý kinh doanh",
      C: "Tầm nhìn",
      D: "Sứ mệnh",
    },
    s: "B",
  },
  {
    id: 8,
    q: "Nội dung của Triết lý kinh doanh bao gồm:",
    a: {
      A: "Sứ mệnh",
      B: "Mục tiêu",
      C: "Hệ thống các giá trị",
      D: "Tất cả các đáp án trên",
    },
    s: "D",
  },
  {
    id: 9,
    q: "______________ xác định mục đích của tổ chức và trả lời câu hỏi: “lý do tồn tại, hoạt động của tổ chức là gì?” ",
    a: {
      A: "Mục tiêu",
      B: "Đánh giá",
      C: "Sứ mệnh",
      D: "Chiến lược",
    },
    s: "C",
  },
  {
    id: 10,
    q: "........của trường Đại học Bách Khoa HN là: “Trở thành một đại học nghiên cứu hàng đầu khu vực với nòng cốt là kỹ thuật và công nghệ, tác động quan trọng vào phát triển nền kinh tế tri thức và góp phần gìn giữ an ninh, hòa bình đất nước, tiên phong trong hệ thống giáo dục đại học Việt Nam”.",
    a: {
      A: "Sứ mệnh",
      B: "Tầm nhìn",
      C: "Chiến lược",
      D: "Mục tiêu",
    },
    s: "B",
  },
  {
    id: 11,
    q: "Đâu không phải là các yếu tố cơ bản khi xây dựng sứ mệnh:",
    a: {
      A: "Hệ thống các giá trị",
      B: "Lịch sử",
      C: "Những năng lực đặc biệt",
      D: "Môi trường của DN (tổ chức)",
    },
    s: "C",
  },
  {
    id: 12,
    q: "Đặc điểm của một bản tuyên bố sứ mệnh là:",
    a: {
      A: "Tập trung vào thị trường chứ không phải sản phẩm cụ thể",
      B: "Cụ thể",
      C: "Khả thi",
      D: "Tất cả các đáp án trên",
    },
    s: "D",
  },
  {
    id: 13,
    q: "Hệ thống các giá trị xác định ....... của doanh nghiệp với những người sở hữu, nhà quản trị, người lao động, khách hàng và các đối tượng hữu quan khác",
    a: {
      A: "Hành vi",
      B: "Nguyên tắc",
      C: "Thái độ",
      D: "Ứng xử",
    },
    s: "C",
  },
  {
    id: 14,
    q: "Nội dung nào sau đây không phải là nội dung của hệ thống các giá trị trong Doanh nghiêp:",
    a: {
      A: "Nguyên tắc của Doanh nghiệp",
      B: "Những năng lực đặc biệt",
      C: "Lòng trung thành và sự cam kết",
      D: "Phong cách ứng xử, giao tiếp",
    },
    s: "D",
  },
  {
    id: 15,
    q: "Ba yếu tố trong mô hình 3 P là:",
    a: {
      A: "Sản phẩm, Lợi nhuận, Con người  ",
      B: "Sản phẩm, Lợi nhuận, Phân phối",
      C: "Lợi nhuận, Phân phối, Con người",
      D: "Lợi nhuận, Phân phối, Giá",
    },
    s: "A",
  },
  {
    id: 16,
    q: "..........là tập hợp các nguyên tắc, chuẩn mực có tác dụng điều chỉnh, đánh giá, hướng dẫn và kiểm soát hành vi của các chủ thể kinh doanh",
    a: {
      A: "Đạo đức",
      B: "Đạo đức kinh doanh",
      C: "Trách nhiệm XH",
      D: "Trách nhiệm đạo đức",
    },
    s: "B",
  },
  {
    id: 17,
    q: "Các nguyên tắc và chuẩn mực của đạo đức kinh doanh không bao gồm",
    a: {
      A: "Tính trung thực",
      B: "Tôn trọng con người",
      C: "Bí mật trung thành với các trách nhiệm đặc biệt",
      D: "Lợi nhuận của Doanh nghiệp",
    },
    s: "D",
  },
  {
    id: 18,
    q: "Đối tượng điều chỉnh của đạo đức kinh doanh là:",
    a: {
      A: "Tầng lớp doanh nhân làm nghề kinh doanh",
      B: "Khách hàng của doanh nhân.",
      C: "Các chủ thể hoạt động kinh doanh",
      D: "Đối thủ cạnh tranh của doanh nghiệp",
    },
    s: "C",
  },
  {
    id: 19,
    q: "Câu nào không phải là vai trò của đạo đức kinh doanh?",
    a: {
      A: "Góp phần làm tăng chất lượng hoạt động của DN",
      B: "Làm cho khách hàng hài lòng",
      C: "Là những hành vi và hoạt động thể hiện mong muốn đóng góp cho cộng đồng và cho XH",
      D: "Tạo ra lợi nhuận bền vững cho DN",
    },
    s: "D",
  },
  {
    id: 20,
    q: "Trách nhiệm XH là nghĩa vụ mà một DN phải thực hiện đối với XH. Có trách nhiệm với XH là tăng đến mức tối đa các ......... và giảm tới mức tối thiểu các......... đối với XH",
    a: {
      A: "Tác động tiêu cực, hậu quả tiêu cực",
      B: "Tác động tích cực, hậu quả tiêu cực",
      C: "Tác động tích cực, trách nhiệm",
      D: "Nghĩa vụ kinh tế, hậu quả tiêu cực",
    },
    s: "C",
  },
  {
    id: 21,
    q: "",
    a: {
      A: "",
      B: "",
      C: "",
      D: "",
    },
    s: "",
  },
];
